using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Batch21_OOPS
{
    internal class BasicInfo
    {
        static void Main()
        {
            Console.WriteLine("Hello World");
            Console.WriteLine("My Name is Shravani");
            Console.WriteLine("I am learning C#");

            Console.ReadLine();
        }
    }
}